version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - C:\Users\João Vitor\Documents\Solar-tech\docker-compose\nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - modulocliente
      - modulofuncionario
      - moduloenviaremail
      - modulocalculadora

  modulocliente:
    image: joaovittorr/modulocliente:latest
    container_name: modulocliente
    expose:
      - 80
    restart: always
    depends_on:
      - db

  modulofuncionario:
    image: joaovittorr/modulofuncionario:latest
    container_name: modulofuncionario
    expose:
      - 80
    restart: always
    depends_on:
      - db
    
  moduloenviaremail:
    image: joaovittorr/moduloenviaremail:latest
    container_name: moduloenviaremail
    expose:
      - 5000
    restart: always
    depends_on:
      - db

  modulocalculadora:
    image: joaovittorr/modulocalculadora:latest
    container_name: modulocalculadora
    expose:
      - 5600
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: solarTech
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
