version: '3.8'

services:
  modulocliente:
    image: joaovittorr/modulocliente:latest
    container_name: modulocliente
    ports:
      - 8080:80
    restart: always
    depends_on:
      - db

  modulofuncionario:
    image: joaovittorr/modulofuncionario:latest
    container_name: modulofuncionario
    ports:
      - 5500:80
    restart: always
    depends_on:
      - db
    
  moduloenviaremail:
    image: joaovittorr/moduloenviaremail:latest
    container_name: moduloenviaremail
    ports:
      - 5000:5000
    restart: always
    depends_on:
      - db

  modulocalculadora:
    image: joaovittorr/modulocalculadora:latest
    container_name: modulocalculadora
    ports:
      - 5600:5600
    restart: always
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: solarTech
      MYSQL_ROOT_PASSWORD: root
    restart: always
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
