version: '3.8'

services:
  modulocliente:
    image: joaovittorr/modulocliente:latest
    container_name: modulocliente
    ports:
      - 8080:80
    restart: always

  modulofuncionario:
    image: joaovittorr/modulofuncionario:latest
    container_name: modulofuncionario
    ports:
      - 5500:80
    restart: always
    
  moduloenviaremail:
    image: joaovittorr/moduloenviaremail:latest
    container_name: moduloenviaremail
    ports:
      - 5000:5000
    restart: always

  modulocalculadora:
    image: joaovittorr/modulocalculadora:latest
    container_name: modulocalculadora
    ports:
      - 5600:5000
    restart: always
